import React from "react";
import { jsPDF } from "jspdf";

const EmployeeBarReport = () => {
  const handleDownloadPDF = () => {
    const doc = new jsPDF();

    // Add the report content
    doc.setFontSize(16);
    doc.text("Employee Analytics Report", 20, 20);
    doc.setFontSize(12);
    doc.text("Date: November 20, 2024", 20, 30);
    doc.text("===================================================================", 20, 35);

    // Section: Project Progress Analytics
    doc.setFontSize(14);
    doc.text("Project Progress Analytics", 20, 45);
    doc.setFontSize(12);
    doc.text("Progress Distribution (Current Project)", 20, 55);

    const progressData = [
      ["Client Name", "Progress (%)", "Status"],
      ["Client-1", "25%", "At Risk"],
      ["Client-2", "40%", "Needs Attention"],
      ["Client-3", "70%", "On Track"],
      ["Client-4", "80%", "Excellent"],
      ["Client-5", "60%", "On Track"],
    ];
    const columnWidths = [30, 40, 40, 70]; // Adjusted widths

    let y = 75; // Initialize y-position for table
    progressData.forEach((row, rowIndex) => {
      let xPosition = 20; // Start at the left margin
      row.forEach((col, colIndex) => {
        doc.text(col, xPosition, y);
        xPosition += columnWidths[colIndex]; // Move to the next column
      });
      y += 10; // Move to the next row
    });

    // Section: Summary
    y += 15; // Add spacing before the summary
    doc.text("Summary:", 20, y);
    doc.text(
      "- High Progress: 2 Clients have achieved progress above 75%.",
      20,
      y + 10
    );
    doc.text(
      "- Moderate Progress: 2 Clients are progressing between 50-75%.",
      20,
      y + 20
    );
    doc.text(
      "- Low Progress: 1 Client is under 50%, needing immediate attention.",
      20,
      y + 30
    );

    // Section: Recommendations for Improvement
    y += 40; // Add spacing before the recommendations
    doc.setFontSize(14);
    doc.text("Recommendations for Improvement", 20, y);
    doc.setFontSize(12);
    doc.text(
      "1. Client-1: Immediate action is required to boost performance.",
      20,
      y + 10
    );
    doc.text(
      "2. Client-2: Organize a status check meeting to identify bottlenecks.",
      20,
      y + 20
    );
    doc.text(
      "3. Continue monitoring Client-5’s progress to ensure it reaches the green zone.",
      20,
      y + 30
    );

    // Footer
    y += 40; // Add spacing before the footer
    doc.setFontSize(12);
    doc.text("Report Generated by: BarChart Analytics Component", 20, y);

    // Save the PDF
    doc.save("Employee_Analytics_Report.pdf");
  };

  return (
    <div className="p-5">
      <h2 className="text-xl font-bold mb-4">Project Status Report</h2>
      <p>Click the button below to download the project status report as a PDF:</p>
      <button
        onClick={handleDownloadPDF}
        className="mt-4 bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600"
      >
        Download PDF
      </button>
    </div>
  );
};

export default EmployeeBarReport;
