import React from "react";
import jsPDF from "jspdf";

const EmployeePieReport = () => {
  const generatePDF = () => {
    const doc = new jsPDF();

    // Set the title
    doc.setFontSize(18);
    doc.text("Employee Task Status Report", 10, 10);

    // Date
    doc.setFontSize(12);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 10, 20);

    // Overview
    doc.setFontSize(14);
    doc.text("Overview", 10, 30);
    doc.setFontSize(12);
    doc.text(
      `This report analyzes the task completion and pending status of an employee over different durations: 
7 days, 30 days, 60 days, and 90 days.`,
      10,
      40
    );

    // Table
    doc.setFontSize(14);
    doc.text("Task Status Summary", 10, 60);

    const tableData = [
      ["Duration", "Completed (%)", "Pending (%)", "Remarks"],
      ["7 Days", "80%", "20%", "Excellent performance."],
      ["30 Days", "70%", "30%", "Good, with room for improvement."],
      ["60 Days", "85%", "15%", "Outstanding performance!"],
      ["90 Days", "65%", "35%", "Needs attention for long-term planning."],
    ];

    // Adjust column spacing
    const columnWidths = [30, 40, 40, 70]; // Adjusted widths
    let yPosition = 80;

    tableData.forEach((row, rowIndex) => {
      let xPosition = 10; // Start at the left margin
      row.forEach((col, colIndex) => {
        doc.text(col, xPosition, yPosition);
        xPosition += columnWidths[colIndex]; // Move to the next column
      });
      yPosition += 10; // Move to the next row
    });

    // Insights and Recommendations
    doc.setFontSize(14);
    doc.text("Insights and Recommendations", 10, 150);
    doc.setFontSize(12);
    doc.text(
      `1. 7-Day Performance: Exceptional task completion rate of 80%. 
Maintain this momentum through regular check-ins and achievable task goals.

2. 30-Day Performance: Task completion dropped slightly to 70%. 
Recommend reviewing pending tasks to mitigate bottlenecks.

3. 60-Day Performance: Excellent progress with an 85% completion rate. 
Reinforce consistent practices and reward productivity.

4. 90-Day Performance: Completion rate dipped to 65%, with 35% pending tasks. 
Suggest strategic planning for long-term task assignments and better time management training.`,
      10,
      160
    );

    // Footer
    doc.text("Generated by Task Analytics Dashboard", 10, 280);

    // Save the PDF
    doc.save("Employee_Task_Status_Report.pdf");
  };

  return (
    <div className="p-5">
      <h2 className="text-xl font-bold mb-4">Task Status Report</h2>
      <p>Click the button below to download the task status report as a PDF:</p>
      <button
        onClick={generatePDF}
        className="mt-4 bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600"
      >
        Download PDF
      </button>
    </div>
  );
};

export default EmployeePieReport;
